apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-operator-system
resources:
  - namespace.yaml
  - https://github.com/adyanth/cloudflare-operator.git/config/default?ref=v0.13.1