apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgAHyHo6uhLrwCP9zrrnqrgtS6x/mg8VN+ZwGUY5nqz788bOxsoidnWBwkGqvbD4dA844weudckCrBJkrDO78JlQv2hh6tWab46xaOH6hXUKZLO1TnoAUFxrI2kDUW3aXIu5YgVAfuduiRmazc/voORQffJxdRHs7Hyr5bwtEMm3pvTFbtMqOyupaAtoegE1A+ZUqjIS7Ipn66iWpV3sQ81S80PJppvg/GneSzNS8HN0N9wiU1jF3nTGH6K/6Mt9/+4lqGdbg+q70H3IDI9ecBYklRVivyQw3qENOzeGAAJAlgvA2IcmsKWPGW+Xxq0cL87ywOurLS8V/Lcz93G+RRzTHwyu+Zrj0sDfjOzS5uVnS+ykyYNSuz3XN3wKxoANqSXIKwc8L2DPRYAXZw+g1XO5sNJl7eSDU88VoGIWfG6jxKYeUvEUOQk5zWD2/jZLnH6cI+LitcLCHtoZFEXPEFG4Mhy/YpnX3/66tjxFbDk6b6/9F6YxS/6DaLhqtQ6OEZj9VWYrP+XsWlcooF9TE76HHh64s3uzJn/GdUYU+JSsLKapySO9flq8E/yIuMD9E1zb3Nw95k4lCItGDZyEsS/XlHkOnGvYxoaSo/TveeDpTT9tw22tak3w7BvaHzTgtY8IQL28PPGtgtAqhgsaMY0MsM36kG07Mrnr361LHFSVmtJX8/jwVMIiO861kLYglhkscFWzp2oEz1KdWCcNhSWVkJV9rF8hSk40jkYGGSeIBm+Its0dwGOw