server:
  persistentVolume:
    size: 16Gi
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: cert-issuer
      # homepage
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: "Monitoring"
      gethomepage.dev/name: "Prometheus"
      gethomepage.dev/app: "prometheus"
      gethomepage.dev/icon: prometheus
      gethomepage.dev/description: "Cluster monitoring"
    hosts:
      - prom.wrenspace.dev
    tls:
      - secretName: prom-tls
        hosts:
          - prom.wrenspace.dev 

