alertmanager:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: cert-issuer
      # homepage
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/group: Monitoring
      gethomepage.dev/app: alertmanager
      gethomepage.dev/name: AlertManager
      gethomepage.dev/description: Prometheus alerts
      gethomepage.dev/icon: alertmanager
    hosts:
      - alerts.wrenspace.dev
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alerts.wrenspace.dev

grafana:
  sidecar:
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      isDefaultDatasource: true
      url: https://stats.wrenspace.dev

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: cert-issuer
      # homepage
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/group: Monitoring
      gethomepage.dev/app: grafana
      gethomepage.dev/name: Grafana
      gethomepage.dev/icon: grafana
      gethomepage.dev/description: Dashboard
    hosts:
      - dash.wrenspace.dev
    tls:
      - secretName: grafana-tls
        hosts:
          - dash.wrenspace.dev

prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: cert-issuer
      # homepage
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/app: prometheus
      gethomepage.dev/name: Prometheus
      gethomepage.dev/description: Performance metrics
      gethomepage.dev/icon: prometheus
      gethomepage.dev/group: Monitoring
      gethomepage.dev/widget.type: prometheus
      gethomepage.dev/widget.url: https://stats.wrenspace.dev
    hosts:
      - stats.wrenspace.dev
    tls:
      - secretName: prom-tls
        hosts:
          - stats.wrenspace.dev