apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - middlewares.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: traefik-values
    namespace: traefik
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true