apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
    cert-manager.io/cluster-issuer: cert-issuer
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/name: "ArgoCD"
    gethomepage.dev/icon: argo-cd
    gethomepage.dev/app: argocd-server
    gethomepage.dev/description: "Kubernetes Continuous Delivery"
    gethomepage.dev/widget.type: argocd
    gethomepage.dev/widget.url: "https://argocd.wrenspace.dev/"
    gethomepage.dev/widget.key: '{{HOMEPAGE_VAR_ARGO_KEY}}'
    gethomepage.dev/weight: "20"
spec:
  ingressClassName: traefik
  rules:
  - host: argocd.wrenspace.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: http
  tls:
  - hosts:
    - argocd.wrenspace.dev
    secretName: argocd-tls