---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - paperless.yaml
  - service.yaml
  - ingress.yaml
  - config.yaml
  - creds.yaml
  - database.yaml
  - nfs-volume.yaml
  - vsftpd.yaml

helmCharts:
  - name: redis-ha
    repo: https://dandydeveloper.github.io/charts
    releaseName: redis-ha
    version: 4.34.13
    namespace: paperless
    valuesInline:
      haproxy:
        enabled: true
      auth: true
      existingSecret: redis-creds
      authKey: password