ports:
  websecure:
    trustedIPs:
      - "10.0.0.0/8"
      - "192.168.0.0/16"
    port: 8443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
    middlewares:
      - kube-system-hsts@kubernetescrd
    http3:
      enabled: true
      advertisedPort: 443
    tls:
      enabled: true
  ldaps:
    port: 6360
    expose:
      default: true
    exposedPort: 636
    protocol: TCP
  mysql:
    port: 3306
    expose:
      default: true
    exposedPort: 3306
    protocol: TCP
dashboard:
  enable: true
  ingressRoute: true
providers:
  kubernetesCRD:
    allowCrossNamespace: true