apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grocy-ldap
  namespace: grocy
spec:
  encryptedData:
    bind-password: AgAsCgSLyBEmYtyr8CDrOdiF8EBjFUXSMWN08UE0n9wfcmZqqqS6QKDxNlLwdlX811H2fyczHODJjySTu0FWQJNRZzb2oTwHcYj9yVoHED+YyPw2nO9WQEQh128s8E6Z/h1+g2AJkOGRm+9ylM8IjfEQiwo+Hx9CjS9rN+DWV8M5hnXQbOT4gmIhT6sY4UPX6ylLTyHzQIdLYADDkPJJwC/WrOHEr4Mr3JYDtXwM3IUykl59v04GWZHXJH4+QLQKrzhYfKjr14rq+rS3+qUkFdqcQz6op47QGkoxZ0UU71YnppioXhdi0/TFJPvXp83zOs2TfEwIDn1IZeV3CrDUhsJG6jeLwuF7IxDZPzIMZ6JL1ZeK5sQUOB1lyEZ6axjLs3ChHGq5UjhGVTP1F6DRW7PcOzfIotb+W+ZoTebwSko2URwMZ04adpcSU2OpB9uq8lwgKsUi3KjykqQ/4uLaEjhiWZQCWg2HXt805qZ4iH+6qUCuKdxEPvCSq+iKGzaT3tF9ZWm0LDlcb1PgmQbCRUmz2Ms+JeausC2lCDzviiA0ST+i4FSTglRLveBl5F1yLgGBa1wER8zipgqTlwQ4KPNwrxUpQcrIamYtXehwS8t2xfX0okepgKn/Rn7V+3+8qK0r6f95+0dTePZyX57VOKNS0wVUbcP7gh57LsWXzfLla5496NRzVY5hXY5UpN0hxEVLeeqAebZxBDKxLQ==