apiVersion: v1
kind: Service
metadata:
  name: grocy
  namespace: grocy
  labels:
    app.kubernetes.io/name: grocy
    app.kubernetes.io/part-of: services
spec:
  type: ClusterIP
  selector:
    app: grocy
  ports:
  - port: 80
    targetPort: 80
    name: http