---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: apprise
  namespace: flux-system
spec:
  type: generic
  address: http://apprise-service.notify.svc.cluster.local:8000/notify/flux