---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: external-ingress
spec:
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 3000
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gitea
  namespace: external-ingress
subsets:
- addresses:
  - ip: 192.168.200.52
  ports:
  - name: app
    port: 3000
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea
  namespace: external-ingress
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Gitea"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "gitea"
    gethomepage.dev/description: "Git repository"
    gethomepage.dev/href: "https://git.wrenspace.dev"
    gethomepage.dev/weight: "20"
    gethomepage.dev/siteMonitor: "https://git.wrenspace.dev"
spec:
  tls:
    - hosts:
        - git.wrenspace.dev
      secretName: gitea
  rules:
    - host: git.wrenspace.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitea
                port:
                  number: 80