---
apiVersion: v1
kind: Service
metadata:
  name: pve
  namespace: external-ingress
spec:
  ports:
  - name: https-pve
    port: 8006
    protocol: TCP
    targetPort: 8006
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pve
  namespace: external-ingress
subsets:
- addresses:
  - ip: 192.168.1.53
  ports:
  - name: https-pve
    port: 8006
    protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: pve-transport
  namespace: external-ingress
spec:
  insecureSkipVerify: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pve
  namespace: external-ingress
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/service.serverstransport: pve-transport@kubernetescrd
spec:
  tls:
    - hosts:
        - pve.wrenspace.dev
      secretName: pve
  rules:
    - host: pve.wrenspace.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pve
                port:
                  number: 8006