---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: external-ingress
spec:
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 8000
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vaultwarden
  namespace: external-ingress
subsets:
- addresses:
  - ip: 192.168.100.6
  ports:
  - name: app
    port: 8000
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
  namespace: external-ingress
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Vaultwarden"
    gethomepage.dev/group: "Core"
    gethomepage.dev/icon: "vaultwarden"
    gethomepage.dev/description: "Password manager"
    gethomepage.dev/href: "https://vault.wrenspace.dev"
    gethomepage.dev/weight: "70"
spec:
  tls:
    - hosts:
        - vault.wrenspace.dev
      secretName: vaultwarden
  rules:
    - host: vault.wrenspace.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vaultwarden
                port:
                  number: 80