---
apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  namespace: external-ingress
spec:
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 80
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: zigbee2mqtt
  namespace: external-ingress
subsets:
- addresses:
  - ip: 192.168.100.2
  ports:
  - name: app
    port: 80
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zigbee2mqtt
  namespace: external-ingress
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Zigbee2MQTT"
    gethomepage.dev/group: "Services"
    gethomepage.dev/icon: "zigbee2mqtt"
    gethomepage.dev/description: "Zigbee bridge"
    gethomepage.dev/href: "https://iot.wrenspace.dev"
    gethomepage.dev/weight: "70"
    gethomepage.dev/siteMonitor: "https://iot.wrenspace.dev"
spec:
  tls:
    - hosts:
        - iot.wrenspace.dev
      secretName: zigbee2mqtt-tls
  rules:
    - host: iot.wrenspace.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zigbee2mqtt
                port:
                  number: 80
