apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - secrets.yaml
  - database.yaml
  - nfs-volume.yaml
  - middlewares.yaml
  - tunnelbinding.yaml

helmCharts:
  - name: redis
    repo: https://charts.bitnami.com/bitnami
    releaseName: redis
    version: 24.0.0
    namespace: nextcloud
    valuesInline:
      architecture: standalone
      auth:
        existingSecret: redis-secret
        existingSecretPasswordKey: password
      master:
        persistence:
          size: 5Gi
        priorityClassName: high-priority

  - name: nextcloud
    repo: https://nextcloud.github.io/helm/
    version: 7.0.2
    releaseName: "nextcloud"
    namespace: nextcloud
    valuesFile: values-nextcloud.yaml