apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - secrets.yaml
  - database.yaml
  - nfs-volume.yaml
  - middlewares.yaml
  - tunnelbinding.yaml

helmCharts:
  - name: redis-ha
    repo: https://dandydeveloper.github.io/charts
    releaseName: redis-ha
    version: 4.34.13
    namespace: nextcloud
    valuesInline:
      haproxy:
        enabled: true
      auth: true
      existingSecret: redis-secret
      authKey: password

  - name: nextcloud
    repo: https://nextcloud.github.io/helm/
    version: 7.0.2
    releaseName: "nextcloud"
    namespace: nextcloud
    valuesFile: values-nextcloud.yaml