apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: komga
  namespace: komga
  labels:
    app.kubernetes.io/name: komga
    app.kubernetes.io/part-of: media
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Komga"
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: "komga"
    gethomepage.dev/description: "Manga and comic library"
    gethomepage.dev/href: "https://manga.wrenspace.dev"
    gethomepage.dev/weight: "10"
spec:
  rules:
  - host: manga.wrenspace.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: komga
            port: 
              name: http
  tls:
    - secretName: komga-tls
      hosts:
        - manga.wrenspace.dev