apiVersion: v1
kind: Service
metadata:
  name: komga
  namespace: komga
  labels:
    app.kubernetes.io/name: komga
    app.kubernetes.io/part-of: media
spec:
  selector:
    app: komga
  ports:
  - port: 25600
    targetPort: 25600
    name: http
