apiVersion: networking.cfargotunnel.com/v1alpha2
kind: ClusterTunnel
metadata:
  name: cluster-tunnel
  namespace: cloudflare-operator-system
spec:
  newTunnel:
    name: cluster-tunnel
  deployPatch: |
    [
      {
        "op": "replace",
        "path": "/spec/template/spec/containers/0/livenessProbe/failureThreshold",
        "value": 5
      },
      {
        "op": "replace",
        "path": "/spec/template/spec/containers/0/livenessProbe/timeoutSeconds",
        "value": 5
      }
    ]
  cloudflare:
    email: coffeeknife@proton.me
    domain: wrenspace.dev
    secret: cloudflare-secret
    accountId: ef8ecca28e80c7cdf1cb68c0a778fe08