apiVersion: networking.cfargotunnel.com/v1alpha2
kind: ClusterTunnel
metadata:
  name: cluster-tunnel
  namespace: cloudflare-operator-system
spec:
  newTunnel:
    name: cluster-tunnel
  deployPatch: |
    {
      "spec": {
        "template": {
          "spec": {
            "containers": [
              {
                "name": "cloudflared",
                "livenessProbe": {
                  "failureThreshold": 5,
                  "timeoutSeconds": 5
                }
              }
            ]
          }
        }
      }
    }
  cloudflare:
    email: coffeeknife@proton.me
    domain: wrenspace.dev
    secret: cloudflare-secret
    accountId: ef8ecca28e80c7cdf1cb68c0a778fe08