apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cloudflare-operator-system
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgBVHvrPmXcgRYTSyBVHb5LBIqsvFPjI1KjGvgnSl//roLF8AYOlukDYU8/CI8ydHYxtRMlzaT0U6asUaO5gG3dzN8KQnWoSLl0GxLqiidgRu2A4JRD8sg7HAPe4sKKe+f2aclLw1v4MIKqBm2Rp+okjYPd32UZmj+ijt0nTIyqJp/Y2YR1FUQP3uHx/636ZZx6Q7bBf7HCzIKlMs1Z1uiJYIwQVc0hgxnYgWZSt7WpjYO0UGRIh1d0RFScuRI5IhtdqaYTo1mqqAVypzBUcVzkLUgSELP3l5MfPl5uuJwccrQ2EQKPnz40qlIZ3Cxa8nZ14mHyZ+zEn7CAnIqsVF4FUWCBmJdATlN+X4QuUXOO1WJkN1zJnSFKxmE390OcjojN2bOXlYFtMnl6q5ZxhOPD7eVl04ghD4OMV02m+ren0392/T3uAHJB903KPhQzdpMIVIbafUoWQgy2QHLagvcIAKvQN2FSXRX+Nh3ZF/vMMZBzGyrB1mFXGcKm5nGo8c6NzcNex/S9MVqDeehGbUanjdd6zZ37a7i3NSnFIJt/4ttGKFI67Ye1wyVvwh994JxolBf1HZOPnSdXm9OxtxWdsM2c/gF0Wg1Y+RVCPyu19qGDBdECCVe1CIhF2mIo2UWZAwFWprWfTZC3yEK+WwQaGqD0oWMmbGUCdk5gXh1/CPltA3vhYZelTZc8cDWyki6kiHf2tquPHolAew2kSvLQ60aN86XIII+FbhczDV82O3qHkj2YC+7HW