apiVersion: apps/v1
kind: Deployment
metadata:
  name: protonmail-bridge
  namespace: protonmail-bridge
  labels:
    app.kubernetes.io/name: protonmail-bridge
    app.kubernetes.io/part-of: infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protonmail-bridge
  template:
    metadata:
      labels:
        app: protonmail-bridge
        app.kubernetes.io/name: protonmail-bridge
    spec:
      containers:
        - name: protonmail-bridge
          image: shenxn/protonmail-bridge:latest
          ports:
            - containerPort: 1143
              name: imap
            - containerPort: 1025
              name: smtp
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /root
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: protonmail-bridge-data
