apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp-relay
  namespace: smtp-relay
  labels:
    app.kubernetes.io/name: smtp-relay
    app.kubernetes.io/part-of: infrastructure
spec:
  selector:
    matchLabels:
      app: smtp-relay
  template:
    metadata:
      labels:
        app: smtp-relay
        app.kubernetes.io/name: smtp-relay
    spec:
      priorityClassName: high-priority
      containers:
      - name: smtp-relay
        image: djjudas21/smtp-relay:0.10.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: smtp-config
          - secretRef:
              name: smtp-secret
        ports:
        - containerPort: 2525
          name: smtp
