apiVersion: v1
kind: Service
metadata:
  name: send
  namespace: smtp-relay
  labels:
    app.kubernetes.io/name: smtp-relay
    app.kubernetes.io/part-of: infrastructure
spec:
  type: ClusterIP
  selector:
    app: smtp-relay
  ports:
  - name: smtp
    port: 25
    targetPort: smtp
