apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lldap-auth
  namespace: authelia
spec:
  encryptedData:
    password: AgAmiuq5vApbZ0Ihov7fvo3bCUzQ7fl0v2IaXRguCn3GwEtjwoEYSWNzllP/wMq4Gm6cV7wH51T1XG7zQs4OPpEBfMyJQWBtqOAXqrOGTwTMDjF6hJSXbuxjkshctO7nOa0MEa/rcrXbzDnPSBNZMBC+v9VafhCbTq4XEGm32ds5A2WyrG8/tYioaOt1zxmuf5bFYpambMSL5YaiQMl3HirE/gh1+9D2FUxBdMrLTrWem3DecqFjH1wq3bHL1lAi0jOBRzZUDZU9Laf1QPq+KSPaFFiZ8xkhUmmjKVQJAw01Njid42WOKdc2Zs79O8woC79O5OBICWXEyhnsXDhFLZI9u+0KT/2r1tq8Xp8thZml188lWrRUEkz1mRLY7CqVYZjCkccDjBa0sEYNJadygl4LFoACDvdK39UxQQ2GKWCdb7M3CrAeJme2BcHYaRPUhuWNLuZ4ieDxV/IyNMwvnTbvmFzNDlBpOpZMkII/eq2roKBX4cfj/i8BFsqQcEAWS7hWRQggvNTPmgXPycQy8V0j5msk1GpgfW+Nxl2TQSsL7n+WbVmvuOp2NAr4Zcg5LJ7haJ3M/vjvxc14BTm9tcEJ0wj9O3FVk2BFFkIeP+kjux/z05yewF98bUak8TLozYhhOf/rlMD2Xxk/hNy3E9OPIcT2QVuHZ6dvQEjUR0VeuHGYIXex+bkoxjFaNvdnU8Bg1orKCBsFC8ozDOm1GrBDTA==
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-auth
  namespace: authelia
spec:
  encryptedData:
    password: AgBjzm0EkId9gWXwatpoYpFhr3MB8rxT+zXOuLBDqSZUY01lvzls8z5RYUCkb533jm+Q+1T/QQURLIrw2UIgjK0p8CFqKd2VnCXzTYuIv/2xqvyPzHn+ZXLavz7JMj4jN4A16G4UWaGHZlzIScyEVGO3v2YiYjcuprV3FY9Te70CfQx/PeN3F8yynVUkpSaTC1CZA84z6ax6LypyXTwjFoyBNX9suIiPHjLx5QhodLNG/vDHNP3cOkV5mJhmAeKbFgU8rZ/+OzOVmuGhkW/HfuYCs2/vL90UIv3TQ4CLCZ2qQRoDd86UYs8W1Miut/SRAd8rhjzS2JtNGa+12Z1S0A25nUyLxLrW/tfu9+opa4GWy4hXplct4gcN5UNi+v/jRyMZSqbnnD6s65OQTcSOTz13QLtGsji4UC+N41bvFAsZx+eaytjmZKmSNG3vExB1r8plMZNMXaL/qq8uk1kagSAznyLCbm7tnFxjY4x58GYl86avxnTy0Pjrn8c73YWw6dp5XbLwDoyw6ZxD8aojuAQG0B9JYl76Ax7nYVYUdvPrj9M0f0ocIQ3BYzy/mRc0e68PovtfCvUw9FnW8afoQYID0tjXU2mLuYFA4wQxVif5eKnjwJfE3laWAkgM0lHJM62Pq4SHWzOg0Hid6Jz44UgeVUKS4xNyTtISzRyY+WK8t8igmNEM/HzN6LKQjzUhD6C8Qr2ibWDLuvjsw1SUdFP8
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-creds
  namespace: authelia
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: session.redis.password.txt