apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: authelia-binding
  namespace: authelia
subjects:
  - kind: Service # Default
    name: authelia
    spec:
      fqdn: auth.wrenspace.dev
      protocol: https
      target: http://authelia.authelia.svc.cluster.local:80
tunnelRef:
  kind: Tunnel # Or ClusterTunnel
  name: cluster-tunnel
  disableDNSUpdates: false