apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - crypto.yaml
  - creds.yaml
  - database.yaml
  - client-secrets.yaml
  - helmrelease.yaml
  - tunnelbinding.yaml

configMapGenerator:
  - name: authelia-values
    namespace: authelia
    files:
      - values.yaml