apiVersion: v1
kind: Service
metadata:
  name: pgvecto-rs-svc
  namespace: immich
  labels:
    app: pgvecto-rs
spec:
  type: ClusterIP
  selector:
    app: pgvecto-rs
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgvecto-rs
  namespace: immich
  labels:
    app: pgvecto-rs
spec:
  serviceName: pgvecto-rs-svc
  replicas: 1
  selector:
    matchLabels:
      app: pgvecto-rs
  template:
    metadata:
      labels:
        app: pgvecto-rs
    spec:
      containers:
      - name: pgvecto-rs
        image: tensorchord/pgvecto-rs:pg14-v0.3.0
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          value: "immich"
        - name: POSTGRES_DB
          value: "immich"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-creds
              key: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 10Gi