apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - secrets.yaml
  - database.yaml
  - nfs-volume.yaml
  - middlewares.yaml
  - tunnelbinding.yaml
  - redis-helmrelease.yaml
  - nextcloud-helmrelease.yaml

configMapGenerator:
  - name: nextcloud-values
    namespace: nextcloud
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true