apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  
  settings.yaml: |
    title: wrenspace.dev
    description: robin homelab homepage
    useEqualHeights: false

    background: https://images.unsplash.com/photo-1509773896068-7fd415d91e2e?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2069
    headerStyle: boxed
    statusStyle: dot

    layout: 
      Media:
        header: false
        style: row 
        columns: 4
      Services:
      Dev/Admin:
      Infrastructure:
      Monitoring:
      Arr:
        header: false
        style: row
        columns: 4

    cardBlur: xl

  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
      - Github:
          - abbr: GH
            href: https://github.com/

    - Social:
        - Matrix:
            - abbr: MX 
              href: https://chat.wrenspace.dev/
        - Reddit:
            - abbr: RE
              href: https://reddit.com/

    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/

    - Media Sourcing:
        - Anna's Archive:
            - abbr: AA
              href: https://annas-archive.org/
        - Nyaasi:
            - abbr: NA
              href: https://nyaa.si/
        - EXTTO:
            - abbr: EX
              href: https://ext.to/
  
  services.yaml: |
    ---
    # For configuration options and examples, please see:
    # https://gethomepage.dev/configs/services/

    - Services:
        - Vaultwarden:
            icon: bitwarden
            description: Password manager
            siteMonitor: https://vault.wrenspace.dev/
            href: https://vault.wrenspace.dev/
            weight: '50'
        - Immich:
            icon: immich
            description: Camera roll backup
            siteMonitor: https://photo.wrenspace.dev/
            href: https://photo.wrenspace.dev/
            weight: '60'

    - Dev/Admin:
        - Gitea:
            icon: gitea
            description: GitHub alternative
            href: https://git.wrenspace.dev/
            siteMonitor: https://git.wrenspace.dev/
        - Opengist:
            icon: opengist
            description: Pastebin
            href: https://gist.wrenspace.dev/
            siteMonitor: https://gist.wrenspace.dev/
        - Minecraft:
            icon: minecraft
            description: Minecraft Server Controller
            href: https://craft.wrenspace.dev/
            siteMonitor: https://craft.wrenspace.dev
        - Synapse:
            icon: matrix
            description: Matrix Server Admin Console
            href: https://synapse.wrenspace.dev/
            siteMonitor: https://synapse.wrenspace.dev/
        - Zigbee2MQTT:
            icon: zigbee2mqtt
            description: Low-Frequency Radio IoT Bridge
            href: https://iot.wrenspace.dev/
            siteMonitor: https://iot.wrenspace.dev/

    - Infrastructure:
        - Etheirys:
            icon: proxmox
            description: VM Host
            weight: 10
            siteMonitor: https://pve.wrenspace.dev/
            href: https://pve.wrenspace.dev/
            widget:
                type: proxmox
                url: https://pve.wrenspace.dev/
                username: {{HOMEPAGE_VAR_PVE_USER}}
                password: {{HOMEPAGE_VAR_PVE_PASS}}
        - Cockpit:
            icon: cockpit
            description: Unix web UI
            weight: 30
            siteMonitor: https://nix.wrenspace.dev/
            href: https://nix.wrenspace.dev/
        - Semaphore:
            icon: ansible
            description: Automation
            siteMonitor: https://ansible.wrenspace.dev/
            weight: 40
            href: https://ansible.wrenspace.dev

    - Monitoring:
        - Traefik:
            icon: traefik
            description: Web and TCP routing
            namespace: traefik
            weight: 10
            app: traefik
            href: https://traefik.wrenspace.dev/dashboard/
        - Longhorn:
            icon: longhorn
            description: Distributed Kubernetes storage
            namespace: longhorn-system
            app: longhorn
            weight: 20
            href: https://longhorn.wrenspace.dev/

  widgets.yaml: |
    ---
    # For configuration options and examples, please see:
    # https://gethomepage.dev/configs/info-widgets/

    - unifi_console:
        url: {{HOMEPAGE_VAR_UNIFI_URL}}
        username: {{HOMEPAGE_VAR_UNIFI_USER}}
        password: {{HOMEPAGE_VAR_UNIFI_PASS}}
        href: {{HOMEPAGE_VAR_UNIFI_URL}}

    - kubernetes:
        cluster:
            # Shows cluster-wide statistics
            show: true
            # Shows the aggregate CPU stats
            cpu: true
            # Shows the aggregate memory stats
            memory: true
            # Shows a custom label
            showLabel: true
            label: "cluster"
        nodes:
            # Shows node-specific statistics
            show: true
            # Shows the CPU for each node
            cpu: true
            # Shows the memory for each node
            memory: true
            # Shows the label, which is always the node name
            showLabel: true

    - search:
        provider: duckduckgo
        target: _blank

    - datetime:
        format:
            hour12: true
            dateStyle: short

    - openmeteo:
        latitude: {{HOMEPAGE_VAR_LAT}}
        longitude: {{HOMEPAGE_VAR_LONG}}
        timezone: {{HOMEPAGE_VAR_TZ}} # optional
        units: imperial # or imperial
        cache: 5 # Time in minutes to cache API responses, to stay within limits
        format: # optional, Intl.NumberFormat options
          maximumFractionDigits: 0
  
  docker.yaml: ""