apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  annotations:
    configmap.reloader.stakater.com/reload: "homepage"
  labels:
    app.kubernetes.io/name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:latest"
          imagePullPolicy: Always
          resources:
            limits:
              memory: 1Gi
              cpu: "1"
            requests:
              memory: 512Mi
              cpu: "0.2"
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "*" # TODO define once ingress is fixed
            - name: HOMEPAGE_VAR_TZ
              value: "America/Chicago"
            # unifi env vars
            - name: HOMEPAGE_VAR_UNIFI_URL
              valueFrom:
                secretKeyRef:
                  name: homepage-env
                  key: unifi_url
            - name: HOMEPAGE_VAR_UNIFI_USER
              valueFrom:
                secretKeyRef:
                  name: homepage-env
                  key: unifi_user
            - name: HOMEPAGE_VAR_UNIFI_PASS
              valueFrom:
                secretKeyRef:
                  name: homepage-env
                  key: unifi_pass
            # location (lat/long)
            - name: HOMEPAGE_VAR_LAT
              valueFrom:
                secretKeyRef:
                  name: homepage-env
                  key: lat
            - name: HOMEPAGE_VAR_LONG
              valueFrom:
                secretKeyRef:
                  name: homepage-env
                  key: long
            # api keys
            - name: HOMEPAGE_VAR_PAPERLESS_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-env
                  key: paperless_key
            - name: HOMEPAGE_VAR_JELLYFIN_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-env
                  key: jellyfin_key
            - name: HOMEPAGE_VAR_JELLYSEERR_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-env
                  key: jellyseerr_key
            - name: HOMEPAGE_VAR_KOMGA_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-env
                  key: komga_key
            - name: HOMEPAGE_VAR_ABSHELF_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-env
                  key: audiobookshelf_key
            - name: HOMEPAGE_VAR_PVE_USER
              valueFrom:
                secretKeyRef:
                  name: homepage-env
                  key: pve_user
            - name: HOMEPAGE_VAR_PVE_PASS
              valueFrom:
                secretKeyRef:
                  name: homepage-env
                  key: pve_pass
            - name: HOMEPAGE_VAR_ARGO_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-env
                  key: argo_key
            - name: HOMEPAGE_VAR_CADDY_API
              valueFrom:
                secretKeyRef:
                  name: homepage-env
                  key: caddy_url
            - name: HOMEPAGE_VAR_NEXTCLOUD_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-env
                  key: nextcloud_key
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config/custom.js
              name: homepage-config
              subPath: custom.js
            - mountPath: /app/config/custom.css
              name: homepage-config
              subPath: custom.css
            - mountPath: /app/config/bookmarks.yaml
              name: homepage-config
              subPath: bookmarks.yaml
            - mountPath: /app/config/docker.yaml
              name: homepage-config
              subPath: docker.yaml
            - mountPath: /app/config/kubernetes.yaml
              name: homepage-config
              subPath: kubernetes.yaml
            - mountPath: /app/config/services.yaml
              name: homepage-config
              subPath: services.yaml
            - mountPath: /app/config/settings.yaml
              name: homepage-config
              subPath: settings.yaml
            - mountPath: /app/config/widgets.yaml
              name: homepage-config
              subPath: widgets.yaml
            - mountPath: /app/config/logs
              name: logs
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: logs
          emptyDir: {}