---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stakater
  namespace: flux-system
spec:
  interval: 24h
  url: https://stakater.github.io/stakater-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: default
  labels:
    app.kubernetes.io/name: reloader
    app.kubernetes.io/part-of: infrastructure
spec:
  interval: 30m
  chart:
    spec:
      chart: reloader
      version: 2.2.7
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
