# Required tokens:
# - RENOVATE_TOKEN: Gitea PAT with write:repository, write:issue scopes
# - GITHUB_COM_TOKEN: GitHub PAT with read:packages scope (for rate limiting)
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-secrets
  namespace: renovate
  labels:
    app.kubernetes.io/name: renovate
    app.kubernetes.io/part-of: infrastructure
spec:
  encryptedData:
    RENOVATE_TOKEN: AgCPF91jaP8Cjat62hMXSqNr8JyCRLCs3fwAJqTUtZ6OA/HMxM/ox5fZGZ//rH1Cq6W6zOoup6w12nUEQc/xGfY6cJ4+WsuEySdFxNiYum8vM9ZfFI30/A9PkzFbVD53z93Ne1rItLtiezMjhix0Z1zDpTl6UF25+/TeJc4CamSuQxPeaxo9vq5ZPRCsdtwdXj6F9LUIggMib3hRPm1eVqvI1XuvNw1jRwEiKFE3oUIxKr7pSZm++X1vVtCA8k5ErFoEd/PtOf+O2XpmspKPyKxT613eEfhawxITjbkUyWqJnwQ59viLJEyqpK2brd7R/D7xur/J0Zlbj4Gr4WIQ+OUU78UeMqNbcQB26yI3fzhaYfY9GsNTprnEvrcUVLTtU4aSYFHsR1Ak2ZM8+svp2sfhzNOdUUXfIwrykO+3Ui+/reJa2hC7fvypu/A+7xWHsd/3dKvuMBMbRZ9yWnQ2NFR0IA4ScdtThCXsObPkrF9vk5Y7IN7AMZ5ylCHCALA61dnx6BSQW/xQ1L7uXYkcIrBjmtYtrRht8bUBi45h8vqpdc4yLvHgZI2uynC6OD8NYu1+wO27MzMiyL8sJ6kS117CiS02eJv3V73dsjHu95HVuhfTPv0aSL+QX/flHpcCG5TJhaej23B+/SuEI3hMev/MhqtC8m06qUbcR8kyJWhuBHIe2VF67w55PsXv1+d30FPj+YA4TaowyKiWtmBRIDkZOjszK4D0W9PKS0cjgaL8k8lXUnuvtoUA
    GITHUB_COM_TOKEN: AgBgiTxY0qJvsYBeUaewu/y0G9+YHbXIegZ+ThQtVNbCIPZ0rnTu3wmvk3jbeJwK1/LxgFqdlS+rkckgtlhXRKT51vUxDY5Guu7gnUZx8PaLT4AZSSbyYVfnE6CdehBnWFduNSVXMmYbWGJYu4XKgovOK2OCEM/Y84sQ7VU0BlMlAnWE73bWtcVywYL8uKHecGLOsOlfxzdETOAfvYm05TF7jhcrFTybEn7bEFYhk5i5TmO+Hlk8G19gWW6q32NUyTQI3x6SyvKwdx6UFDPOA+wUaklezjLit2fx7QA+spU/6AwacJE4wNhCYstNoQ717U1GREymLlhfTtsEGhAD9c4agbOKu8S7cDXQGAnlovLk9PwS3sDmAMfwh4cLZAum9N+mvAvqTiwgiL7yW/Ua2eteabqrnMJ1GtYmM0yBX6TSSVcgCor9MHi3oLv+VUTzQh824J98d7l/T86NmOnFImJY8OzFREDAhrUaJFUIdOLZm05UxgLuGd7DIbd1JNqy/WfIdCy5NKXJcSethUMm41IzsRApr2KwiS2Mdz97eq3p68y1D5QkOV2/v6DuaRcwvc23OljghnNKifcFQnbELnl0IKcgoVi7JTcV2prByFh1icImy9x6zmT70VQkHmMqCm+2BkZbmUdft6mFj7tn5rM+6lMNaQK9Y3HgD227co4hXHrYewKy4YzgnV6a2t0FA6SgtUP07qeHRlF32+idUwzqkc16A7bRbUrgHEyFG39QI9U4eGyGcDKj
  template:
    metadata:
      name: renovate-secrets
      namespace: renovate
      labels:
        app.kubernetes.io/name: renovate
        app.kubernetes.io/part-of: infrastructure