# Required tokens:
# - RENOVATE_TOKEN: Gitea PAT with write:repository, write:issue scopes
# - GITHUB_COM_TOKEN: GitHub PAT with read:packages scope (for rate limiting)
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-secrets
  namespace: renovate
  labels:
    app.kubernetes.io/name: renovate
    app.kubernetes.io/part-of: infrastructure
spec:
  encryptedData:
    RENOVATE_TOKEN: AgBYY/dxkGv49cn44BPLFNLkB7OwAVfo/cfdvqSmvHFleYxJCcto/sT+RzCBvRzgy/Y2UWIu0fAdd3R8iRFREEPjaQBr69f4dHnL5p3mrwDJQIa6Y4FDYUra1XgYTcCv6W2CIJLOvKtstBICB76/MXv1lQS6chmsP7zFLV5g1vYa1C6lYoeXMLq0nAVlBS612U3q21tYSglhrQf1ikCUkMN1F+DN8lbyzp5sHObvKL11b3WTEFRGoDs37FR/Ps4Yixaw9hK867Ij6vtZ0grBOc8ysnW1NtU0iCLtJvo+0Ov0gMtkuBsN5q3Ns9bgDyFBDsSgj6mHQ5RGH5xrE4l0OB4r6YBNp7rnCz2Kr4cNQZCvPHQewl05oQ3X4ftawMSjFVj2q3soblwTu8GlF1zHKCIocVp9fGv2stp3mg4c1OjhHa2ZOB3e3h1av2GaNvdT3vhlggpydX1UbP4eE6q1yDiBDfN+hbLK1+PiDNUZRxBqhxLvWQ5OsvgdYYgTNvdJKtUmrWeWt3sFHH+jEbqxdFvJht0Fb0o/8QS/E1TPURQ3DEYVNks1hrYv85PjPulPIq5vr8S8m1ssuW50FCfiwj9e3RFYCLXMe6BETUd2esBMTxg+QPoGQYOPLFvvoQodTuiomaWMZvybu+TaIZBiDxbbz519w2VQe7Jl2FOX756iVti6JNhc45q7zNnhRIUH6BEHQOWfLJSTManMr2dw6+mEU5I7GCfFzKuYwga67UQjw3VvOKYIahXR
    GITHUB_COM_TOKEN: AgBgiTxY0qJvsYBeUaewu/y0G9+YHbXIegZ+ThQtVNbCIPZ0rnTu3wmvk3jbeJwK1/LxgFqdlS+rkckgtlhXRKT51vUxDY5Guu7gnUZx8PaLT4AZSSbyYVfnE6CdehBnWFduNSVXMmYbWGJYu4XKgovOK2OCEM/Y84sQ7VU0BlMlAnWE73bWtcVywYL8uKHecGLOsOlfxzdETOAfvYm05TF7jhcrFTybEn7bEFYhk5i5TmO+Hlk8G19gWW6q32NUyTQI3x6SyvKwdx6UFDPOA+wUaklezjLit2fx7QA+spU/6AwacJE4wNhCYstNoQ717U1GREymLlhfTtsEGhAD9c4agbOKu8S7cDXQGAnlovLk9PwS3sDmAMfwh4cLZAum9N+mvAvqTiwgiL7yW/Ua2eteabqrnMJ1GtYmM0yBX6TSSVcgCor9MHi3oLv+VUTzQh824J98d7l/T86NmOnFImJY8OzFREDAhrUaJFUIdOLZm05UxgLuGd7DIbd1JNqy/WfIdCy5NKXJcSethUMm41IzsRApr2KwiS2Mdz97eq3p68y1D5QkOV2/v6DuaRcwvc23OljghnNKifcFQnbELnl0IKcgoVi7JTcV2prByFh1icImy9x6zmT70VQkHmMqCm+2BkZbmUdft6mFj7tn5rM+6lMNaQK9Y3HgD227co4hXHrYewKy4YzgnV6a2t0FA6SgtUP07qeHRlF32+idUwzqkc16A7bRbUrgHEyFG39QI9U4eGyGcDKj
  template:
    metadata:
      name: renovate-secrets
      namespace: renovate
      labels:
        app.kubernetes.io/name: renovate
        app.kubernetes.io/part-of: infrastructure