# Required tokens:
# - RENOVATE_TOKEN: Gitea PAT with write:repository, write:issue scopes
# - GITHUB_COM_TOKEN: GitHub PAT with read:packages scope (for rate limiting)
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-secrets
  namespace: renovate
  labels:
    app.kubernetes.io/name: renovate
    app.kubernetes.io/part-of: infrastructure
spec:
  encryptedData:
    RENOVATE_TOKEN: AgA6fGUtIhsa9f4QfYK0RCuVfvlP3vFQAPrDUHg+xTisZwyh4S2jbX+2GkCtOhUGcpJMEP+KxTyXyZfWiF82m/87aWPy2GGDddnKLhlePstGMe1rdQSeXeyyUpbjsPx9DX3Zsa9H8bvjjrNMjyaTq6AXM1EQgfednBaa1nM+L3kUWUpcP2JWAZ3xitz9nlpYSZ9SOcX98wOYGDsW7pOUdYlyyCmKAXqQbSP849+nLXVpNb8Vs1N/daC6OPRwsjBbmwX0pOy0akkcm4RhSOW0mJ50fP4SATCkAwDqHdk0390EqRZcR++IOg/4MuVr8ZxiKkF6tjoJfVR0v5LvJBhf6T92rRn4S3yqCubJmffX2QnuOuLyLVae6lAYM7VemUC9WyU5X9aPZw+yI40c45jNbF+UrfB4WhptoO2lbw7OCGSNh5U/x8bbdN4GJ0WJn+pI0EwZf9km6sRpLzp14N5bFbFtXUSDCg8aEk1WV5/7jDR3o2QW+u3gjYvoVoHx++pz0Rrj/AAt3skFwH1UrAmEVIVO0a7Gy0efyte5x2qx7bTvg29pC2R0xSBOVYNstnOgZqh2HxIDT+ffhQnIMYmEPeNxF8+jtfhr6wplFfaA64sNw3PBNk68C3nDf0jgWRjB3OhcPA5spYnggcaZzp/8bYbS2Y9XLXAJCDhB1BX0Hu32IvtzjGgrESctyztd8AHomTiWX0Hu+IQJE6B3FR9rS9uMkD2GaYbO5IO9RlRllLAxEvT0oYl87+nH
    GITHUB_COM_TOKEN: AgBgiTxY0qJvsYBeUaewu/y0G9+YHbXIegZ+ThQtVNbCIPZ0rnTu3wmvk3jbeJwK1/LxgFqdlS+rkckgtlhXRKT51vUxDY5Guu7gnUZx8PaLT4AZSSbyYVfnE6CdehBnWFduNSVXMmYbWGJYu4XKgovOK2OCEM/Y84sQ7VU0BlMlAnWE73bWtcVywYL8uKHecGLOsOlfxzdETOAfvYm05TF7jhcrFTybEn7bEFYhk5i5TmO+Hlk8G19gWW6q32NUyTQI3x6SyvKwdx6UFDPOA+wUaklezjLit2fx7QA+spU/6AwacJE4wNhCYstNoQ717U1GREymLlhfTtsEGhAD9c4agbOKu8S7cDXQGAnlovLk9PwS3sDmAMfwh4cLZAum9N+mvAvqTiwgiL7yW/Ua2eteabqrnMJ1GtYmM0yBX6TSSVcgCor9MHi3oLv+VUTzQh824J98d7l/T86NmOnFImJY8OzFREDAhrUaJFUIdOLZm05UxgLuGd7DIbd1JNqy/WfIdCy5NKXJcSethUMm41IzsRApr2KwiS2Mdz97eq3p68y1D5QkOV2/v6DuaRcwvc23OljghnNKifcFQnbELnl0IKcgoVi7JTcV2prByFh1icImy9x6zmT70VQkHmMqCm+2BkZbmUdft6mFj7tn5rM+6lMNaQK9Y3HgD227co4hXHrYewKy4YzgnV6a2t0FA6SgtUP07qeHRlF32+idUwzqkc16A7bRbUrgHEyFG39QI9U4eGyGcDKj
  template:
    metadata:
      name: renovate-secrets
      namespace: renovate
      labels:
        app.kubernetes.io/name: renovate
        app.kubernetes.io/part-of: infrastructure