apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress
data:
  WORDPRESS_DB_HOST: mariadb-port.mariadb-sys.svc.cluster.local
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_NAME: wordpress-db
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: WORDPRESS_DB_PASSWORD