apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: wordpress-db
  namespace: wordpress
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb-sys
  characterSet: utf8
  collate: utf8_general_ci
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: wordpress
  namespace: wordpress
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb-sys
  passwordSecretKeyRef:
    name: mariadb-secret
    key: mariadb-password
  maxUserConnections: 20
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: wordpress-perm
  namespace: wordpress
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb-sys
  privileges:
    - "ALL"
  database: "wordpress-db"
  table: "*"
  username: wordpress
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: wordpress-perm2
  namespace: wordpress
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb-sys
  privileges:
    - "SELECT"
  database: "mysql"
  table: "user"
  username: wordpress