apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: wordpress-db
  namespace: wordpress
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb-sys
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: wordpress
  namespace: wordpress
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb-sys
  passwordSecretKeyRef:
    name: wordpress-secret
    key: WORDPRESS_DB_PASSWORD
  maxUserConnections: 20
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: wordpress-perm
  namespace: wordpress
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb-sys
  privileges:
    - "ALL"
  database: "wordpress-db"
  table: "*"
  username: wordpress