apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wordpress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wordpress
    spec:
      volumes:
        - name: wordpress
          persistentVolumeClaim:
            claimName: wordpress
      containers:
      - name: wordpress
        image: wordpress:6.8.3-php8.4
        volumeMounts:
          - name: wordpress
            mountPath: /var/www/html
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        envFrom:
          - configMapRef:
              name: wordpress-config
          - secretRef:
              name: wordpress-secret
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
spec:
  selector:
    app.kubernetes.io/name: wordpress
  ports:
  - port: 80
    targetPort: 80
