apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app.kubernetes.io/name: wordpress
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/icon: wordpress
    gethomepage.dev/name: Wordpress
    gethomepage.dev/description: 'Robin and Erika site'
    gethomepage.dev/group: Media
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer
spec:
  tls:
    - hosts:
      - wp.wrenspace.dev
      secretName: wp.wrenspace.dev-tls
  rules:
  - host: wp.wrenspace.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: wordpress
            port: 
              number: 80
