---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - database.yaml

helmCharts:
  - name: wordpress
    repo: oci://registry-1.docker.io/bitnamicharts/
    releaseName: wordpress
    version: 26.0.0
    namespace: wordpress
    valuesFile: wordpress.values.yaml