apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wordpress-secret
  namespace: wordpress
spec:
  encryptedData:
    wordpress-password: AgCGOKoBKdNXTvG3krav++xjPnQLeEud45WDxOasgAPnxUOwonazc+6Y60+vAedtbmASjo12lxGolW2g/deV1gwNr6/G1/YD5ivbwxdx/jHX3Zf3+hsRyfiDcsx4zJRvbID/Maax3g6d3YRJ2kvn7OrJtWoEnskSV31ViKqF0nDOF/Lryi6yZ2my2tm+hv1VNcpoaiJlPS8zVZmOXV5+n+2GmjL5bHpRmeclJRbj3sNeT/LySEynejcmU1kecasTN7lizH4LyCKi+VMZU/SlfxyaVEAhzM1/cgCiCbDRN9zp34s2+Zf8+rjiCMelj0EQ8eux0LkVzG5W9id79n5MUndc1P+3oMaokHzyWfrRQXB3WrAJAUpdNt1VRcjFu6/mYRUTD7W/uGYrizU4w1Z0RVSR+qvNa+dpILkk9m580rHD737c2KLlwhweCBm+0HeK/RODSvvITk1+V5KX6NjOtzFlJspHQBsLQPMfdcNgO2erwtRl+0kFcI19aB/y2RiQXYf/kYHDiPlnC8AHqoxqeLBOFqgoiib+g8B+IpOhbI4DItRGSA/7IoupwyoIOFqYHLeCqxsAXQ8Ja05sAdaAlt9bUdK1Vl8cNdhd5DYzE4nOBfl4J1aRYMuR4w/sUvXF//Nb5p9gpF1wK1UR6XWcheHKlQpSmTXlh1+P2auTaCPIfaKo9vu+XT/od3OD2U+hKNmYkqmsbn3bdSirFQ==
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-secret
  namespace: wordpress
spec:
  encryptedData:
    mariadb-password: AgBQpP9zAb4joo3rZdivxK0eIUVFt0EOwSqyj9jK18Vv4m7x10KK7Kv3PuJvchlEZknbGP5BOCW4zzTSmdBzQBWnct8+s5TavZJbp9ymjqHYAqM+pyBDs3XHX2k4LatLG3j3geK0BxQkih+swLDUjO/H1es3IHGzTuMxraBKXyL6qrL988JVlFgbi3sPKxPRHvY1BalPmrQuwCQFQl0azmXXufHewOHs6yL+ssvpF9PKM+kCIf/WNubxXPcBGTgNfggmAW4fYpcxN/EzhX0K53c7Ko8Txwz4PykLtN+uW0l+0QPh1gZ0EqPAfB/UtBcOU1NcfLgPlrE9GV9NQPxvjUlLXQ1PTzT6vWzDDbtEbykb9YqLcGiQCQ4h7uO5sD0NggeBZDhrQkg+2WBHA6sDbKexLtsv/wBiwqazXTFV8b22Okv3C2B4bBmyZ0i2IutYCCIrhrU1zEMdfExseZJAcI9RDGZSMk9rNBEP/RmJoH4WrBrpGMoLRClmVl/G47eQzGQbvmlY14giOZ/UM53bh/gvA2ZdrO+HVTkJjI9D0zSiHIUBf7ck5Hbg5k/xmnGZWIH/vRZCrzkNj/xcQf/4DoZ/RG2pYuxzTPvR5CDm4kaQXHaUGtIX3zIBAHtcSw+PCQ689D5xVOk+bb8k+wbiT1MQCmROIpmuR+9kNtnZJPxPGE0A/SK8jbQByXeXOYrFZqda28ru6ePvmf1aMhqDctiki0+uRnQQVtSTXtLdEW+PnA==