---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: anza-labs
  namespace: flux-system
spec:
  interval: 24h
  url: https://anza-labs.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lubelogger
  namespace: lubelogger
  labels:
    app.kubernetes.io/name: lubelogger
    app.kubernetes.io/part-of: services
spec:
  interval: 30m
  chart:
    spec:
      chart: lubelogger
      version: 1.4.2
      sourceRef:
        kind: HelmRepository
        name: anza-labs
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: lubelogger-values
