apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrelease.yaml
  - secrets.yaml
  - mail-secret.yaml

configMapGenerator:
  - name: lubelogger-values
    namespace: lubelogger
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
