---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lubelogger-oidc-values
  namespace: lubelogger
  labels:
    app.kubernetes.io/name: lubelogger
    app.kubernetes.io/part-of: services
spec:
  encryptedData:
    oidc.clientSecret: AgCUkDnJZtJkxln62UK/Mx36hcQH2VnCikjPHCPpwU33ytJrdGcbdeuhaTO2ZlN9iT79MljEITn4PNt0hhlIW/Frtjj2jC1VXRvwkmKNKoDD5cPt1MlScOW9lgLsRZN5Ilg7g71ZYiavEnbAOGQEbrtx4W4NbEuT+Z+ahXGiACo2uP3FTWgtWzuC41MsnGJz2MWXmm4aiwXU36s7/gYw33zJpXVMzhrT5PlNKzdAxPonA0VsysOTZ3BTlUGw4LfRaWeQalPHnlGE56VBt6ujYo5mo2E/C3ztpZQIrWKtjTLwMxGaj/GeqC7iw+vBJVhPcm4qw4mfDU5ir7tOj4thxeaT6hj25jZGQGP1EFdpVYpy7hWPL6QEnXTCGgserSeTK/HWkV6Uyj/nU354eK8oIGUHqZNs/XOgHsibhz6NyPn+Awws1KEmDJluNE5U5bi0PxPmovPIdOAs20oMQqYQQ0GJYj23D/BVdwVWo05z+snyOp9HHdrA7d3HqnLXKwsi/iksgCDZhxlutmV5RBZFUVHXGTla3Y4tCyF0m5etqreRrtJtk94vuwxPCH8QpuuNM5jLY8hp11UEhf7KxaPewlZ5fkrJ6C1ZK3mskGJ3SRdWTeOxU942gAG/VvDVD0ldGoBGkUuJzVtSY32nwPwqEuYMnJsOlc1IDRYT+ZVZoV5R/RjatrCRNqh5iT+Cb+Hzp8E6oJ2tkmmJ/tw0ZFW/G3SeokDAW/59BO/+ghiaPzISTGaFHuD+3dRjGbrAkZBb7R25/Q/9+uIln69XMxVA9iEEdT+4fZKefr0=
  template:
    metadata:
      name: lubelogger-oidc-values
      namespace: lubelogger
      labels:
        app.kubernetes.io/name: lubelogger
        app.kubernetes.io/part-of: services
