# This secret is in flux-system namespace for postBuild substitution
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lubelogger-oidc-secret
  namespace: flux-system
  labels:
    app.kubernetes.io/name: lubelogger
    app.kubernetes.io/part-of: services
spec:
  encryptedData:
    clientSecret: AgA2l9ExwIF3SOsUhJFzf/EszRKTLA0tVNsLfK/inc/IbwnFdoePZUuVz1+CE+fgi3dogiY5RIBAAlAO/FXiSplCW41KPIWr8/DvonYOO4K8Jjw98YSFik7faUDqdgZDHLGN/g3mzHs+xKkqWN5/fi94nwPUNNBfNHZKQHvn4MID0/Gdxu8Ifdpi+GLfrNA4gp79NO/tDh/bgku0XsV3ng4a0b4nll6gVKM5Rcm0PO8VthoWpHZ0pYejqpP6RS2lGwjZPkoKTmyA9Uji8kXaSTKrm4RjAq6ExL0SSXcQM96wjFP22jJeS63XCRuVQ4qwdy5www6709ATeNwemVOr7QsG9P3gQqLY46vR7Xsudv4oq6TMk1o9EWKH3XqtuMT9ywTKzGkpz3Dl8A5R4v7RniU/8HqNe7D4s3MvBm7xWV8mvPYdEAs8BJOyQYTh4aR/eNqKjNoSK7TxxX2tvdfSfqAvq+FJQDx3OjCVG6OWF147l4UxCHOA9Gk94bBgkGmZDA4mqezlb4D4KioLiHHW0rAiWzttg98tPi3r0h0SDKKcidN91ST4mDjzXP6TfOpa2ZNS/xbYPQveaYKFvS2n/svFQEA4JH7vAp3jsVFmY5NJtCIACQelWHm+3dnDUiri+8oPn51aOFKFCuZunIkdFFePlNx71QSY5lAkyalofBwARZBR9TkLAi/3zXg2JNdNY1F+96XfWGjR4rCDm5TMFvhn7wPEbbrEt6/+ybIYUeeCCSQvDrxKreXRtOzB99wOZ1ha3auYbDyJN7Tpdn6fvxTYDacsswXiTKE=
  template:
    metadata:
      name: lubelogger-oidc-secret
      namespace: flux-system
      labels:
        app.kubernetes.io/name: lubelogger
        app.kubernetes.io/part-of: services
