---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lubelogger-oidc-values
  namespace: lubelogger
  labels:
    app.kubernetes.io/name: lubelogger
    app.kubernetes.io/part-of: services
spec:
  encryptedData:
    values.yaml: AgCeZC6aGVuMFbOXVL2Ssckk1S3wyeTHzJh2ZzRGBrnGjMKmAAYlhPg/e6TPSWp8N4NOGuMiL5vOdrd+csoEoIJ7vDjbZHoos+kCih6CqvMxmR+3mD7FbSayeNRn2zhXlmQCH8wW+aTHeinjIal1LSX4YYH3NwwWmNxGxg1FCy6W9YTFB+J9pB4xMG04qnr0smYWmUCKzrVXUEWWjvcFTauh5vpFNFAeNr7FYKbx1FPykKPiM1KXINKBPZTlwe18AOPxiNVLP/BK2KM0Ed8NgyIyM+ZQolpqVBWP6/6ge4IqVetaLjEg9o16MQDRlIxZw6eXNwnp6HRVuXwoZS31nk3qgsGsabXxpmi2jKMGYx9M7FnJPZ3mhTjU54asgk64uY1xPJwzK/GViflMDjpnrZCUAQ4dCSdvuH1WMCJvFBktieA0YXIUTWSpCZKEud6qDPZdJ3qkw3c3dfdbhY6Fvw3boUYFehI6Y9aKkPwu+taO8+wPrw2BA+KKkfHQW92+6IyJbVYRCnJmmWKJBHpO+zdwMWKoSydU5f+6dpMky8hcfhfhahL9KPQj/7Pg2ZKyaKSHk7MtuMwYuMMu8GF1Zhyx2nNTUvznwn4bgDC3RQzBSMRAQHKjxTZcUAxMvTEdNvDmH1k0sFZ3lUg3hXifCBnb+ZXvTBmGBIujLdSBwnR+JMQM6xY8jSVloELLdAY9Eyb+tXSdK06gr3Xn18BkPjKR7oHhZPtaHeDy9QCa6kKRy4LQNGLsbTnE0EVpN3bh150gStLnshaTcL85Gl+wLTJ6xfbviPO8B2oQaznaf994NM/nghZDm+2OJgJ7kZakPag=
  template:
    metadata:
      name: lubelogger-oidc-values
      namespace: lubelogger
      labels:
        app.kubernetes.io/name: lubelogger
        app.kubernetes.io/part-of: services
