---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lubelogger-oidc-secret
  namespace: lubelogger
  labels:
    app.kubernetes.io/name: lubelogger
    app.kubernetes.io/part-of: services
spec:
  encryptedData:
    clientSecret: AgCBJEJgsdBBXkk15c823RTXs6M072SUaOCMK/3zEheJF9LOhkksHzY+JaCUtVCjBXnFczYaLMk/ahoEYQCUQyBZa6AE6rKyJoiqsQlADEIlyloMJKzSGlly0epNCYQlGqRRBFsKADvucB5eKWHLHH5pka5iUE8ZrGCllq7vv5oK6HTfLaFSo9qX5o57WwGpEmJJ//NkixM74S3EDAJkNPO208JsFS/XfzENeaUGi54TUq1ZUv0Dm1bEk5TLagBjowG0FJh0floASzEmiYRkYnVH7DU+f8D2azAtcvDCpMItki94PpC3wh+heRmV0Ao6eHBUyTCGM+Sui74cUyOIyS31XkT72C4Sf/BahMCTupUJK7nCZbfAmszBcRg9wCgZw+0+CnuyGWNB+7gZ4Cu7RL8FcqG8hhhkziwS+38wLIoTe7N6IJ5iwsph1DSXBWqgQ+Wgutoz/uG/lDvdDKIYDg1xWQRNUNzpeX0TEKDLx5VX+N+NfQQkvYna4H+tyh+UcLxEgwuMUOROwYL5mefTmMtK7RueoIQXCzMRR5wcLZoQYOi9YQR7vBfl002UOdD1lpO2PIoAjJ87vcjwSGGy8qlKTj305PjoRhieQoMifzHjInU6UeGkV1LjBuM7c8LTMAP26GhaxYV4A//GDDOSV1qJVRbPzgiD+IXPlZch4/sLRlyY+28Tcm8aOtIF8qxLHf9thKrvk2yvwyfOhSiFXFDbcz3tv8u20Ugmzrv0o1FTw4XFJi6er3jQ7FdrKNHz37W27tKtPdRMUUJd54jnn6aAK72sGdXQt/Q=
  template:
    metadata:
      name: lubelogger-oidc-secret
      namespace: lubelogger
      labels:
        app.kubernetes.io/name: lubelogger
        app.kubernetes.io/part-of: services
