image:
  repository: ghcr.io/hargata/lubelogger
  tag: v1.5.7

secret:
  create: true
  emailServer: send.smtp-relay.svc.cluster.local
  emailFrom: lubelogger@wrenspace.dev
  port: 25
  username: ""
  password: ""

persistence:
  enabled: true
  storageClass: longhorn
  size: 1Gi

oidc:
  enabled: true
  create: true
  providerName: Authelia
  clientId: lubelogger
  clientSecret: "${clientSecret}"
  authURL: https://auth.wrenspace.dev/api/oidc/authorization
  tokenURL: https://auth.wrenspace.dev/api/oidc/token
  redirectURL: https://car.wrenspace.dev/Login/RemoteAuth
  scope: "openid email"
  validateState: false
  usePKCE: true
  disableRegularLogin: false
  userInfoURL: https://auth.wrenspace.dev/api/oidc/userinfo
  logOutURL: ""

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "LubeLogger"
    gethomepage.dev/group: "Services"
    gethomepage.dev/icon: "si-car"
    gethomepage.dev/description: "Vehicle maintenance tracker"
  hosts:
    - host: car.wrenspace.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: lubelogger-tls
      hosts:
        - car.wrenspace.dev
