apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homarr-secret
  namespace: homarr
spec:
  encryptedData:
    SECRET_ENCRYPTION_KEY: AgAmmERwil/nXT0iAcHtZWdj0ZJjicB/YArSXsNYg4Koj9qBwvtXu4OHsl2nAma+hgT7FGyllgHiTjk/3kAXDebShvWPgxzT4U/TsU49f++IEw7P89xwpKBXCBBWtTBnrOUptF/IJhbYj8SyT0iOqCB1+Dx5+hIGfOhJNkz1cczB3suFgYqso186XfEXorb6DDcUFwG07TRd1zEB1jqacy5ML1jL6nPYtRDN0LQ42Z1hNODWqG5G3kQdW4wegpkyZuymxxfgXH3JG9HcyFXXdmTCnQTm5mqMKmceJadTxiJdFKz0b6PR7wdKqaNjKo19djZapDSYCKCyLCOM2CZYiamGMiQ0SdfoZGJcUzlyCuxq9eqP4wcdseQ7lJ2CwzZZ3ZXs6S8tnfA4NsNT1TRbENOTahWhHOCnROUQoZbEm+x5dA1NflcB/z3Vsn+0hGRYkklbgBRxvTbCgpq/yhswvXW216/tKPbzqAwsLnfKcAzlZ739EiR9f0lBiH8U56CJZrjT4JJtXEnCTta5IFDiT1Xd+pRWQ+SXoYy2nKufeZ7yZfyzGWOGRD1X72+FMv1PaT6mZ4fae4ba2DPcpe9ztmE6ZJxELEnwx/tJ0HnSJg085kgXZMUuMXI79e5BDjc+F6GKcZmMo/ZNbce4mIQukTTlXP508J8+L9TdLXtrxoWVz6XPgVUNsLLmGd+FEl8QiQsoiPlbaD1jJv09ajKEA0zbpnz+4ahrwqC7LE7xd7r2FdaGDhjaf1/MkMBdNI8nkslk8jhLXLO6Udni049JxU/U