---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mariadb-operator
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.mariadb.com/mariadb-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
  namespace: mariadb-sys
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: database
    app.kubernetes.io/component: crds
spec:
  interval: 30m
  chart:
    spec:
      chart: mariadb-operator-crds
      version: 25.10.4
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: mariadb-sys
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: database
    app.kubernetes.io/component: operator
spec:
  interval: 30m
  dependsOn:
    - name: mariadb-operator-crds
  chart:
    spec:
      chart: mariadb-operator
      version: 25.10.4
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
  values:
    currentNamespaceOnly: false
    priorityClassName: high-priority