apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mysql-in
  namespace: mariadb-sys
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: database
spec:
  entryPoints:
    - mysql

  routes:
  - match: HostSNI(`*`)
    services:
    - name: mariadb-port
      port: 3306