apiVersion: v1
kind: Service
metadata:
  name: mariadb-port
  namespace: mariadb-sys
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: database
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 31623
      protocol: TCP
  selector:
    app.kubernetes.io/name: mariadb