apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - helmrelease.yaml
  - oauth-secret.yaml

commonLabels:
  app: grafana

configMapGenerator:
  - name: grafana-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
