apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
  namespace: paperless
data:
  PAPERLESS_URL: "https://file.wrenspace.dev"
  PAPERLESS_CSRF_COOKIE_SAMESITE: "Lax"
  PAPERLESS_SESSION_COOKIE_SAMESITE: "Lax"
  PAPERLESS_CSRF_TRUSTED_ORIGINS: "https://wrenspace.dev,https://auth.wrenspace.dev,https://file.wrenspace.dev"
  PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
  PAPERLESS_PORT: "8000"
  PAPERLESS_TIME_ZONE: America/Chicago
  # file processing
  PAPERLESS_CONSUMER_ENABLE_BARCODES: "true"
  PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE: "true"
  # db
  PAPERLESS_DBHOST: mariadb-port.mariadb-sys.svc.cluster.local
  PAPERLESS_DBENGINE: mariadb
  PAPERLESS_DBPORT: "3306"
  PAPERLESS_DBNAME: paperless-db
  PAPERLESS_DBUSER: paperless
  PAPERLESS_DB_READ_CACHE_ENABLED: "true"
  # branding
  PAPERLESS_APP_TITLE: Yuri Documents
  # SSO
  PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
  PAPERLESS_SOCIAL_AUTO_SIGNUP: "true"
  PAPERLESS_SOCIAL_ACCOUNT_SYNC_GROUPS: "true"
  PAPERLESS_DISABLE_REGULAR_LOGIN: "false"
  PAPERLESS_REDIRECT_LOGIN_TO_SSO: "false"
  PAPERLESS_ACCOUNT_SESSION_REMEMBER: "true"
  # email sending
  PAPERLESS_EMAIL_HOST: send.smtp-relay.svc.cluster.local
  PAPERLESS_EMAIL_FROM: Paperless <admin@wrenspace.dev>
  # consume
  PAPERLESS_CONSUMPTION_DIR: ../consume/
  PAPERLESS_CONSUMER_POLLING: "30"