apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/part-of: services
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-hsts@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Paperless"
    gethomepage.dev/group: "Core"
    gethomepage.dev/icon: "paperless-ngx"
    gethomepage.dev/description: "Document management"
    gethomepage.dev/href: "https://file.wrenspace.dev"
    gethomepage.dev/weight: "30"
spec:
  rules:
    - host: file.wrenspace.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paperless
                port:
                  name: http
  tls:
  - hosts:
      - file.wrenspace.dev
    secretName: paperless