apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: paperless-headers
  namespace: paperless
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Host: "file.wrenspace.dev"
      X-Forwarded-Port: "443"