apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - env.yaml
  - secrets.yaml
  - nfs-vol.yaml
  - postgres.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: immich-values
    namespace: immich
    files:
      - values.immich.yaml
    options:
      disableNameSuffixHash: true