---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-pv
  namespace: immich
spec:
  storageClassName: immich-nfs
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/birdpool/photo
    server: 192.168.1.69
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pvc
  namespace: immich
spec:
  storageClassName: immich-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi