apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - helmrelease.yaml

commonLabels:
  app: loki

configMapGenerator:
  - name: loki-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
