---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubito
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.kubito.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arr-stack
  namespace: arr-stack
spec:
  interval: 30m
  chart:
    spec:
      chart: servarr
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: kubito
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: arr-stack-values
      valuesKey: values.arr.yaml