apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - middlewares.yaml
  - unpackerr.yaml
  - lidatube.yaml
  - qbittorrent-helmrelease.yaml
  - organizr-helmrelease.yaml
  - arr-helmrelease.yaml

configMapGenerator:
  - name: qbittorrent-values
    namespace: arr-stack
    files:
      - values.qbit.yaml
    options:
      disableNameSuffixHash: true
  - name: arr-stack-values
    namespace: arr-stack
    files:
      - values.arr.yaml
    options:
      disableNameSuffixHash: true
  - name: organizr-values
    namespace: arr-stack
    files:
      - values.organizr.yaml
    options:
      disableNameSuffixHash: true