---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8sathome
  namespace: flux-system
spec:
  interval: 1h
  url: https://k8s-at-home.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: organizr
  namespace: arr-stack
spec:
  interval: 30m
  chart:
    spec:
      chart: organizr
      version: 7.4.2
      sourceRef:
        kind: HelmRepository
        name: k8sathome
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: organizr-values
    valuesKey: values.organizr.yaml