---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rtomik
  namespace: flux-system
spec:
  interval: 24h
  url: https://rtomik.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: arr-stack
spec:
  interval: 30m
  chart:
    spec:
      chart: qbittorrent-vpn
      version: 0.0.1
      sourceRef:
        kind: HelmRepository
        name: rtomik
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: qbittorrent-values
      valuesKey: values.qbit.yaml