apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - helmrelease.yaml
  - mdns-bridge.yaml

configMapGenerator:
  - name: hass-values
    namespace: hass
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true