configuration:
  enabled: true
  forceInit: true
  logger:
    default: warning
    logs:
      custom_components.mail_and_packages: debug
  trusted_proxies:
    - 10.0.0.0/8

addons.codeserver.enabled: true

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: longhorn

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: cert-issuer
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Home Assistant"
    gethomepage.dev/group: "Core"
    gethomepage.dev/icon: "home-assistant"
    gethomepage.dev/description: "Home automation"
    gethomepage.dev/href: "https://home.wrenspace.dev/auth/oidc/welcome"
    gethomepage.dev/weight: "50"
  hosts:
    - host: home.wrenspace.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - home.wrenspace.dev
      secretName: hass-tls